Fix build errors about `missing with_docs` in complex projects
-- Backstory: when I added this crate as a dependency in my large
project, I started running into mysterious build errors related to
building bevy_reflect itself (!). It seems this is a known issue for
project using custom builds or proc-macros.
-- See the closed issue https://github.com/bevyengine/bevy/issues/18668
for context and the workaround used here.
-- I was able to use this as a dependency and to build all the examples.
-- For searchability, this is the kind of error I was getting (tens of times):
```
error[E0599]: no method named `with_docs` found for struct `type_info::OpaqueInfo` in the current scope
   --> .../.cargo/registry/src/index.crates.io-1949cf8c6b5b557f/bevy_reflect-0.17.0/src/impls/alloc/collections/binary_heap.rs:3:1
    |
  3 | impl_reflect_opaque!(::alloc::collections::BinaryHeap<T: Clone>(Clone));
    | ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ method not found in `type_info::OpaqueInfo`
    |
   ::: .../.cargo/registry/src/index.crates.io-1949cf8c6b5b557f/bevy_reflect-0.17.0/src/type_info.rs:580:1
    |
580 | pub struct OpaqueInfo {
    | --------------------- method `with_docs` not found for this struct
    |
    = note: this error originates in the macro `impl_reflect_opaque` (in Nightly builds, run with -Z macro-backtrace for more info)
```